// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrdujvuppwoamgbbwkoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyZHVqdnVwcHdvYW1nYmJ3a295Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODgzMjYsImV4cCI6MjA2NjI2NDMyNn0.aO7SFqzB4GUGb8U5aXgyHo8jvMKKTMQwMhe2Nbg7XVU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);